### ISSUE TITLE
main.cpp 中夹爪的角度怎么来的？

### ISSUE THREAD

**Issue by taoxiantong** [Suyixiu/robot_sim#6]
> gripper_angle = 0.0033113173071797 * grasp_distance + 0.127363015998244; 

上面这句怎了来的，我想着用仿真控制robotiq，但是只能控制关节，我想知道关节和robotiq的两个tip间的宽度对应关系。

**Comment by Suyixiu** [comment]
这个是我根据我用的这个爪子在这个仿真器里面抓东西的宽度来算出来的爪子闭合系数，抓得太紧东西会飞走
